In [1]:
import numpy as np
import pandas as pd
import pprint, pickle
#from pycaret.utils import version
#version()
import pandas as pd
import numpy as np
#from itertools import chain
from sklearn.ensemble import IsolationForest
from sklearn.impute import KNNImputer


In [2]:
name_list=['chathura','hasitha','yohan','ravindu','geemanthi','jayasanka','derek','nirmana','dasith','bimsara']

In [3]:
c=['side','front']
#direction='right'
#vid_no=3

In [4]:
#name_list=['ishin']

In [5]:
for cam in c:
    if cam == 'front':
        d=['front','back']
    elif cam == 'side':
        d=['right','left']

    for direction in d:
        for name in name_list:
            for vid_no in range(1, 4):
                print(name)
                s_file_S = open('parameters/Static/{}/{}/{}_{}_{}.pkl'.format(cam,direction,name,direction,vid_no), 'rb')
                s_file_D = open('parameters/Dynamic/{}/{}/{}_{}_{}.pkl'.format(cam,direction,name,direction,vid_no), 'rb')
                sT_S = pickle.load(s_file_S)
                sT_D = pickle.load(s_file_D)
                s_file_S.close()
                s_file_D.close()
                #print(sT_S)
                #print(sT_D)

                merged_df=[]
                gait_merged=[]
                data=[]
                data_missing=[]
                imputer=[]
                data_imputed=[]
                data_NaN_handled=[]
                model=[]
                outliers=[]
                data_outliered=[]
                time=[]
                output=[]

                # merge the two dataframes based on the common 'time' column
                merged_df = pd.merge(sT_S, sT_D, on='time', how='outer')

                # print the merged dataframe
                merged_df = merged_df.sort_values(by='time')
                merged_df = merged_df.reset_index(drop=True)
                count_col = merged_df.pop("count")
                merged_df.insert(0, "count", count_col)

                merged_df

                ## drop count & time columns
                gait_merged=merged_df.iloc[:, 2:]
                gait_merged
                print('gait_merged.shape',gait_merged.shape)

                #handle missing NAN values
                data = gait_merged


                # Loop over each column in the dataset
                for col in data.columns:
                    # Calculate mean of non-NaN values in the current column
                    col_mean = data[col][~data[col].isna()].mean()

                    # Replace NaN values in the current column with the calculated mean
                    data[col] = data[col].fillna(col_mean)

                # Apply mean imputation to handle missing values

                # Convert the imputed data back to a Pandas DataFrame
                data_NaN_handled = pd.DataFrame(data, columns=data.columns)

                # Save the imputed data to a CSV file
                print('data_NaN_handled.shape',data_NaN_handled.shape)
                data_NaN_handled

                #Handling Outliers

                # Define the Isolation Forest model with a contamination parameter of 0.05 (i.e., 5% of data points are expected to be outliers)
                model = IsolationForest(n_estimators=100, max_samples='auto', contamination=0.05, random_state=42)

                # Fit the model to the data and predict the outliers
                model.fit(data_NaN_handled)
                outliers = model.predict(data_NaN_handled)
                print(outliers)

                # Remove the outliers from the dataset
                data_outliered = data_NaN_handled[outliers == 1]

                # Print the number of outliers detected and the number of data points remaining after outlier removal
                print(f'Number of outliers detected: {len(data_NaN_handled[outliers == -1])}')
                print(f'Number of data points remaining after outlier removal: {len(data_outliered)}')

                time = merged_df[['time']]

                # merge time dataframe with data_outliered dataframe
                data_outliered.insert(0, 'time', merged_df['time'])
                data_outliered = data_outliered.reset_index(drop=True)


                # show data_outliered dataframe with the corresponding time column
                print('data_outliered.shape',data_outliered.shape)
                print(data_outliered)

                output = open('feature_vector/{}/{}/FV_{}_{}.pkl'.format(cam,direction,name,vid_no), 'wb')
                pickle.dump(data_outliered, output)
                output.close()
                print(cam,direction,name,vid_no)
                print("____________________________________________________")
    


chathura
gait_merged.shape (6, 56)
data_NaN_handled.shape (6, 56)


/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.900000             1.349872              1.338067            0.524864   
1  2.433333             1.250626              1.351073            0.519489   
2  3.000000             1.311683              1.296826            0.535490   
3  3.566667             1.270731              1.361292            0.537342   
4  4.133333             1.373674              1.308752            0.537279   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.547882            0.412736             0.469015      0.287622   
1             0.560115            0.396591             0.471024      0.282546   
2             0.568994            0.408922             0.448197      0.285756   
3             0.581611            0.409023             0.467527      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  2.066667             1.280808              1.376064            0.513282   
1  2.600000             1.310650              1.297259            0.527299   
2  3.166667             1.261249              1.358281            0.528309   
3  3.666667             1.318029              1.294130            0.536622   
4  4.300000             1.287707              1.379193            0.542975   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.555741            0.415286             0.469488      0.282036   
1             0.557166            0.390680             0.462868      0.277924   
2             0.577043            0.401006             0.465939      0.285066   
3             0.573442            0.401198             0.440652      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  2.133333             1.292149              1.383521            0.522952   
1  2.666667             1.325603              1.300359            0.527061   
2  3.333333             1.258709              1.371132            0.547448   
3  3.800000             1.332863              1.320303            0.540959   
4  4.433333             1.252142              1.372420            0.538298   
5  4.933333             1.324735              1.288056            0.522043   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.555010            0.396979             0.471768      0.288556   
1             0.549803            0.385119             0.460273      0.275160   
2             0.575101            0.437965             0.478457      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.52             1.305601              1.421370            0.525757   
1  2.12             1.320560              1.346832            0.531352   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.547018            0.421027             0.494650      0.294329   
1             0.552807            0.419976             0.490163      0.316695   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.323721        0.663253  ...   0.909454  0.751633  0.968476   
1       0.332173        0.660818  ...   0.891476  0.688879  0.977648   

   visi_kal   visi_sa  visi_flr  visi_fll   visi_tr   visi_po   visi_sw  
0  0.968476  0.989885  0.883588  0.900365  0.751633  0.996831  0.879905  
1  0.977648  0.987944  0.902450  0.87958

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.24             1.301260              1.358101            0.507888   
1  1.92             1.290532              1.298038            0.525810   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.529285            0.427898             0.448536      0.303748   
1             0.520716            0.417943             0.496211      0.301256   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.317365        0.657684  ...   0.862364  0.683661  0.968768   
1       0.340963        0.643109  ...   0.891685  0.746832  0.983037   

   visi_kal   visi_sa  visi_flr  visi_fll   visi_tr   visi_po   visi_sw  
0  0.968768  0.990255  0.852433  0.888348  0.781854  0.996300  0.855411  
1  0.983037  0.982400  0.912209  0.91220

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.400000             1.322213              1.351751            0.561941   
1  2.000000             1.230007              1.361478            0.543809   
2  2.533333             1.249832              1.291192            0.557671   
3  3.133333             1.212258              1.363617            0.531370   
4  3.700000             1.277036              1.298001            0.518631   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.587846            0.461871             0.528568      0.314313   
1             0.597391            0.460741             0.517219      0.308268   
2             0.605265            0.448628             0.516725      0.302704   
3             0.604053            0.440491             0.499881      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1 -1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.900000             1.273850              1.399061            0.548309   
1  1.500000             1.354787              1.342129            0.560296   
2  1.966667             1.270875              1.367001            0.548249   
3  2.566667             1.255895              1.279906            0.566691   
4  3.633333             1.251275              1.276076            0.520946   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.602017            0.424501             0.544224      0.317442   
1             0.594253            0.468508             0.559062      0.325091   
2             0.605549            0.458640             0.527330      0.297385   
3             0.610466            0.475785             0.521778      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.900000             1.265574              1.377044            0.537801   
1  1.466667             1.363457              1.361171            0.560332   
2  2.000000             1.300034              1.406368            0.565024   
3  2.566667             1.239495              1.280860            0.565875   
4  3.166667             1.225986              1.350447            0.552644   
5  3.700000             1.218471              1.248172            0.537293   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.601186            0.428758             0.538614      0.307432   
1             0.593754            0.463380             0.561059      0.323261   
2             0.612948            0.467359             0.532379      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.933333             1.281366              1.281583            0.517465   
1  2.533333             1.230621              1.357985            0.530141   
2  3.133333             1.269832              1.259220            0.528690   
3  3.700000             1.232475              1.375005            0.536651   
4  4.300000             1.248158              1.233294            0.516174   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.539390            0.411261             0.478992      0.288946   
1             0.540807            0.409670             0.482611      0.296791   
2             0.544346            0.412353             0.488933      0.294969   
3             0.568320            0.413982             0.484082      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.233333             1.296283              1.262713            0.495061   
1  1.766667             1.224828              1.351198            0.521007   
2  2.333333             1.270994              1.270526            0.525635   
3  2.933333             1.218982              1.310259            0.532390   
4  3.566667             1.261978              1.266157            0.539643   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.541596            0.391699             0.501914      0.310555   
1             0.544685            0.417712             0.495611      0.310757   
2             0.541954            0.424127             0.490879      0.324767   
3             0.565746            0.428887             0.478210      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 4
data_outliered.shape (4, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.92             1.473683              1.422608            0.555472   
1  1.56             1.383700              1.516306            0.559239   
2  2.20             1.419248              1.416272            0.547448   
3  2.84             1.456480              1.567643            0.585007   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.573954            0.464477             0.527863      0.297651   
1             0.584227            0.451728             0.517429      0.290439   
2             0.578534            0.463475             0.498527      0.295545   
3             0.607861            0.494491             0.531151      0.309011   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.337684 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1 -1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.72             1.468461              1.459426            0.557977   
1  1.36             1.452101              1.605611            0.570821   
2  2.60             1.450854              1.571018            0.566353   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.572040            0.455505             0.526737      0.290571   
1             0.605795            0.476996             0.505019      0.299776   
2             0.601133            0.493932             0.524989      0.306319   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.341473        0.749415  ...   0.903073  0.692458  0.977258   
1       0.323292        0.747650  ...   0.877053  0.719762  0.951216   
2       0.328584        0.74789

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 4
data_outliered.shape (4, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.92             1.297153              1.417214            0.512123   
1  1.56             1.370637              1.342853            0.498648   
2  2.16             1.277486              1.390337            0.524345   
3  2.72             1.343972              1.335403            0.516106   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.549993            0.422599             0.447265      0.298234   
1             0.530118            0.384172             0.460409      0.274301   
2             0.557648            0.443936             0.412870      0.322053   
3             0.549934            0.395424             0.486134      0.305118   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.290877 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


side right jayasanka 3
____________________________________________________
derek
gait_merged.shape (5, 56)
data_NaN_handled.shape (5, 56)


/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 4
data_outliered.shape (4, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.366667             1.363464              1.355241            0.549192   
1  1.866667             1.205624              1.384577            0.543498   
2  2.433333             1.286854              1.279367            0.561352   
3  3.000000             1.194665              1.313991            0.562851   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.601989            0.434851             0.521539      0.307305   
1             0.588942            0.439058             0.497834      0.306841   
2             0.590292            0.439143             0.495259      0.312174   
3             0.593078            0.448435             0.498430      0.322990   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.000000             1.392319              1.343777            0.532650   
1  1.533333             1.216355              1.385666            0.542344   
2  2.100000             1.273151              1.270490            0.558167   
3  2.700000             1.187378              1.308211            0.556588   
4  3.266667             1.273940              1.265525            0.574289   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.603655            0.429480             0.518899      0.307065   
1             0.589792            0.450943             0.505543      0.321286   
2             0.583728            0.442830             0.507927      0.313158   
3             0.593851            0.444279             0.492181      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.933333             1.225202              1.390345            0.532256   
1  1.366667             1.251471              1.290449            0.538765   
2  1.533333             1.370261              1.353645            0.553499   
3  2.033333             1.193112              1.354491            0.557592   
4  2.633333             1.264772              1.269215            0.584147   
5  3.233333             1.195551              1.313153            0.568068   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.603874            0.430278             0.518810      0.319405   
1             0.591297            0.440752             0.490650      0.335171   
2             0.607928            0.447376             0.548670      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.833333             1.232455              1.401195            0.524107   
1  1.233333             1.336314              1.389632            0.540911   
2  1.400000             1.337731              1.307468            0.532860   
3  1.900000             1.258454              1.397180            0.532451   
4  2.466667             1.308167              1.294580            0.548461   
5  3.066667             1.187651              1.341209            0.546264   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.594671            0.378604             0.511641      0.288515   
1             0.561683            0.455981             0.456455      0.285763   
2             0.586649            0.379666             0.502099      0.284845   
3             0.595593            0.404194             0.503837      0.303564   
4             0.583

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (7, 56)
data_NaN_handled.shape (7, 56)
[ 1  1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.133333             1.230676              1.393144            0.534215   
1  1.600000             1.320002              1.390753            0.544109   
2  1.733333             1.330584              1.327401            0.542104   
3  2.233333             1.259269              1.391236            0.542469   
4  2.800000             1.308887              1.302785            0.557530   
5  3.433333             1.226880              1.377048            0.558456   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.592254            0.408141             0.514827      0.299191   
1             0.563732            0.449091             0.476526      0.313473   
2            

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1 -1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 4
data_outliered.shape (4, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.300000             1.316115              1.338055            0.523917   
1  1.833333             1.222424              1.381467            0.504471   
2  2.400000             1.313969              1.321347            0.533311   
3  3.466667             1.317770              1.326124            0.529461   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.537837            0.407333             0.473780      0.310352   
1             0.548426            0.397126             0.473498      0.303023   
2             0.551496            0.425703             0.460545      0.315855   
3             0.561858            0.418623             0.459550      0.318864   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


side right dasith 3
____________________________________________________
bimsara
gait_merged.shape (6, 56)
data_NaN_handled.shape (6, 56)
[ 1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.500000             1.320225              1.296044            0.507121   
1  2.000000             1.194133              1.319498            0.504004   
2  2.533333             1.268740              1.277721            0.529392   
3  3.066667             1.213065              1.314969            0.507820   
4  3.666667             1.248590              1.257326            0.505617   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.541653            0.400703             0.513946      0.285913   
1             0.539850            0.407196             0.490354      0.295878   
2            

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.600000             1.214560              1.331839            0.523911   
1  2.133333             1.323305              1.337266            0.516469   
2  2.733333             1.276352              1.392395            0.513740   
3  3.266667             1.293751              1.302851            0.523660   
4  3.833333             1.185182              1.291137            0.500399   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.559881            0.414472             0.513180      0.320071   
1             0.551050            0.393036             0.521453      0.306233   
2             0.550592            0.437077             0.559517      0.318198   
3             0.547783            0.382322             0.535249      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


side left chathura 1
____________________________________________________
chathura
gait_merged.shape (7, 56)
data_NaN_handled.shape (7, 56)


/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.700000             1.426427              1.299282            0.563275   
1  2.300000             1.344175              1.333229            0.558868   
2  2.833333             1.376828              1.265786            0.564320   
3  3.400000             1.304256              1.275586            0.553267   
4  3.933333             1.374344              1.256496            0.566734   
5  4.500000             1.319910              1.274130            0.559617   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.524228            0.483753             0.400250      0.313414   
1             0.509281            0.469088             0.380799      0.320279   
2             0.514917            0.476552             0.369659      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1 -1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.88             1.380446              1.404819            0.513276   
1  2.08             1.264684              1.317476            0.533039   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.516613            0.507997             0.447396      0.308292   
1             0.505623            0.478462             0.426388      0.312479   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.286546        0.681788  ...   0.995034  0.735295  0.703041   
1       0.282761        0.629623  ...   0.993710  0.739127  0.774035   

   visi_kal   visi_sa  visi_flr  visi_fll   visi_tr   visi_po   visi_sw  
0  0.703041  0.091332  0.958910  0.958910  0.872711  0.998717  0.902897  
1  0.774035  0.150453  0.937857  0.93785

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


side left hasitha 3
____________________________________________________
yohan
gait_merged.shape (6, 56)
data_NaN_handled.shape (6, 56)


/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.500000             1.336794              1.222977            0.603158   
1  2.100000             1.299055              1.294816            0.587459   
2  2.633333             1.316768              1.194568            0.589974   
3  3.200000             1.306125              1.303972            0.582358   
4  3.733333             1.378279              1.232694            0.584499   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.536676            0.515220             0.412065      0.329927   
1             0.552100            0.546992             0.445425      0.342875   
2             0.550288            0.519740             0.424369      0.339750   
3             0.546632            0.532982             0.425368      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


side left yohan 3
____________________________________________________
ravindu
gait_merged.shape (6, 56)
data_NaN_handled.shape (6, 56)
[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.566667             1.300382              1.324390            0.532162   
1  2.166667             1.330020              1.228260            0.517304   
2  2.800000             1.235072              1.259384            0.494510   
3  3.400000             1.345079              1.217972            0.536161   
4  3.933333             1.261314              1.260252            0.517701   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.508168            0.491124             0.409729      0.325556   
1             0.519517            0.478809             0.422698      0.310753   
2             0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  2.033333             1.293165              1.284233            0.518678   
1  2.700000             1.306457              1.209594            0.519335   
2  3.266667             1.260588              1.266772            0.512240   
3  3.900000             1.344019              1.219152            0.539524   
4  4.466667             1.280632              1.310768            0.529829   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.495488            0.489174             0.397467      0.333902   
1             0.517841            0.465408             0.398206      0.322938   
2             0.510824            0.473365             0.447091      0.320226   
3             0.511918            0.463677             0.450763      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (4, 56)
data_NaN_handled.shape (4, 56)
[ 1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.92             1.499609              1.458965            0.589675   
1  1.56             1.491192              1.487616            0.605560   
2  2.20             1.511725              1.412009            0.592077   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.551930            0.551032             0.451414      0.331283   
1             0.574294            0.515838             0.431612      0.325396   
2             0.559235            0.508303             0.440836      0.320752   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.287306        0.749167  ...   0.991675  0.698817  0.645141   
1       0.302340        0.757096  ...   0.9932

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.48             1.502778              1.381850            0.585257   
1  2.08             1.476064              1.475938            0.580080   
2  2.76             1.527137              1.377894            0.584850   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.558110            0.528410             0.426013      0.322526   
1             0.574766            0.525478             0.436998      0.326631   
2             0.554425            0.508931             0.453686      0.313168   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.284268        0.767396  ...   0.990284  0.742637  0.673933   
1       0.301708        0.753770  ...   0.994723  0.712386  0.651339   
2       0.300886        0.76435

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


data_NaN_handled.shape (4, 56)
[-1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.56             1.236454              1.264531            0.522301   
1  2.16             1.341508              1.212600            0.526717   
2  2.72             1.227423              1.208413            0.522965   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.494240            0.488515             0.354090      0.320780   
1             0.496424            0.428774             0.415230      0.296958   
2             0.487879            0.499198             0.393282      0.309466   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.269049        0.615685  ...   0.991082  0.762199  0.613526   
1       0.286266        0.650810  ...   0.984324  0.796774  0.711726   


/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1 -1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 57)
   time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  0.76             1.389713              1.236355            0.534453   
1  1.96             1.406132              1.241844            0.536326   
2  2.56             1.233277              1.243472            0.518272   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.492088            0.438331             0.391413      0.304043   
1             0.502113            0.447812             0.406167      0.302232   
2             0.483163            0.508205             0.378635      0.322913   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar  \
0       0.287339        0.659149  ...   0.987423  0.711472  0.617626   
1       0.287630        0.683971  ...   0.987345  0.775732  0.716292   
2       0.279529        0.61152

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 4
data_outliered.shape (4, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.166667             1.378852              1.241508            0.580741   
1  1.766667             1.307253              1.306772            0.585698   
2  2.366667             1.345581              1.183967            0.565643   
3  2.966667             1.324815              1.295462            0.590806   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.538335            0.510269             0.431843      0.317636   
1             0.546897            0.533663             0.430516      0.325513   
2             0.530326            0.496443             0.419498      0.314714   
3             0.551618            0.525168             0.444980      0.337397   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (7, 56)
data_NaN_handled.shape (7, 56)
[ 1  1  1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.566667             1.330086              1.329856            0.571946   
1  2.133333             1.367212              1.226006            0.594507   
2  2.633333             1.310345              1.304406            0.578799   
3  3.233333             1.316526              1.192599            0.582211   
4  3.766667             1.233157              1.268813            0.567270   
5  4.400000             1.345784              1.219371            0.589834   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.524732            0.541154             0.441689      0.342449   
1             0.521435            0.487473             0.429776      0.324348   
2            

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1  1 -1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 6
data_outliered.shape (6, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.633333             1.330497              1.325113            0.575042   
1  2.266667             1.362560              1.225537            0.600533   
2  2.766667             1.308191              1.300464            0.581828   
3  3.333333             1.319801              1.195852            0.584087   
4  3.900000             1.249036              1.269164            0.568928   
5  5.033333             1.247219              1.291963            0.562825   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.525764            0.530006             0.431370      0.333076   
1             0.520968            0.482731             0.425456      0.324686   
2             0.540525            0.504202             0.421010      0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.566667             1.336376              1.332244            0.536150   
1  2.100000             1.365906              1.223097            0.551626   
2  2.600000             1.269954              1.270712            0.523421   
3  3.166667             1.351398              1.219130            0.548119   
4  3.700000             1.271294              1.269694            0.546687   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.512484            0.491024             0.399059      0.343573   
1             0.509185            0.486048             0.362453      0.340851   
2             0.500937            0.445540             0.387894      0.325618   
3             0.500789            0.476924             0.380370      0.333149   
4             0.498017            0.444082             0.412930      0.336055   

   arm_right_av

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 4
data_outliered.shape (4, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.433333             1.343170              1.229060            0.545242   
1  2.033333             1.298458              1.292714            0.515691   
2  2.566667             1.318582              1.175052            0.522842   
3  3.100000             1.236468              1.218361            0.535826   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.508397            0.440228             0.373797      0.331321   
1             0.509728            0.495947             0.442892      0.347752   
2             0.493846            0.441610             0.397929      0.313215   
3             0.504808            0.440822             0.396269      0.315808   

   arm_right_avg  thigh_left_avg  ...  visi_hakl   visi_ta  visi_kar 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (6, 56)
data_NaN_handled.shape (6, 56)
[-1  1  1  1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 5
data_outliered.shape (5, 57)
       time  lower_body_left_avg  lower_body_right_avg  upper_arm_left_avg  \
0  1.900000             1.355585              1.227235            0.546988   
1  2.500000             1.324924              1.305460            0.530298   
2  3.033333             1.313527              1.186623            0.529972   
3  3.600000             1.240589              1.239104            0.541968   
4  4.100000             1.282100              1.165712            0.511970   

   upper_arm_right_avg  lower_arm_left_avg  lower_arm_right_avg  arm_left_avg  \
0             0.503946            0.454412             0.377424      0.326227   
1             0.520400            0.498649             0.421201      0.333430   
2             0.493650            0.433563             0.380265      0.306010   
3            

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   1.2                  1.348559                0.346343         0.201886   
1   2.3                  1.334870                0.342632         0.198108   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.476640                       0.496256   
1                      0.478674                       0.499296   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.427181                       0.441547   
1                      0.434139                       0.423213   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.052465                 1.075768  ...  0.305364  5.639848   
1                1.058572                 1.058046  ...  0.280089  2.772497   

      

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.166667                  1.331028                0.341845   
1  2.300000                  1.313571                0.342200   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.197877                      0.467443   
1         0.198147                      0.480182   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.494416                      0.430309   
1                       0.498694                      0.433285   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.436909                1.040568   
1                       0.421720                1.059435   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.064638  ...  0.247146  3.919089  0.099985  0.9323

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  0.56                  1.487246                0.394601          0.21813   
1  1.96                  1.387229                0.376511          0.21193   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.519393                       0.535659   
1                      0.494379                       0.504498   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.486201                       0.467580   
1                      0.475942                       0.453895   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll         po  \
0                1.165687                 1.154410  ...  0.243285  14.285365   
1                1.129942                 1.100578  ...  0.251067   5.945292   

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  1.28                  1.392327                 0.37755         0.213058   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.486287                       0.513362   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.467549                        0.46712   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.112047                 1.125927  ...  0.296094  5.406534   

         sw  visi_stl  visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po  \
0  0.090212  0.913305   0.963268   0.955826  0.923642  0.948467  0.999231   

    visi_sw  
0  0.705958  

[1 rows x 49 columns]
front front hasitha 2
____________________________________________________
hasitha
gait_mer

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (2, 48)
data_NaN_handled.shape (2, 48)
[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.733333                  1.382811                0.383304   
1  1.866667                  1.389507                0.389989   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.219395                      0.569022   
1         0.218365                      0.562828   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.566046                      0.517006   
1                       0.567124                      0.513730   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.532044                1.237895   
1                       0.527082                1.229996   

   df_arm_length_right_avg  ...       fll         po        sw  visi_stl  \
0          

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.766667                  1.391933                0.384526   
1  1.866667                  1.385227                0.387876   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.218004                      0.559794   
1         0.219707                      0.561765   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.556077                      0.509972   
1                       0.560924                      0.516472   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.525804                1.218534   
1                       0.527324                1.229635   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.237030  ...  0.299948  7.555647  0.106388  0.9197

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.733333                  1.414330                0.346275   
1  1.900000                  1.407189                0.343496   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.198801                      0.495910   
1         0.197267                      0.498727   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.530776                      0.441370   
1                       0.530550                      0.432698   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.469171                1.079942   
1                       0.471221                1.067398   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.143304  ...  0.295479  4.132539  0.113964  0.8925

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   2.4                  1.603719                0.385054         0.222682   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.564417                       0.569994   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.521825                       0.495791   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.246646                 1.231758  ...  0.352577  5.514248   

         sw  visi_stl  visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po  \
0  0.106709  0.882725   0.900909   0.892506  0.798787  0.868859  0.994448   

    visi_sw  
0  0.435799  

[1 rows x 49 columns]
front front geemanthi 1
____________________________________________________
geemanthi
gait

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  0.20                  1.815968                0.324876         0.202600   
1  0.68                  0.652972                0.344448         0.209635   
2  0.92                  1.119904                0.344088         0.193282   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.581744                       0.523939   
1                      0.606967                       0.576453   
2                      0.484859                       0.474600   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.578508                       0.743765   
1                      0.509543                       0.608839   
2                      0.488154                       0.459462   

   df_arm_length_left_avg 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 3
data_outliered.shape (3, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  0.20                  1.815968                0.324876         0.202600   
1  0.68                  0.652972                0.344448         0.209635   
2  0.92                  1.119904                0.344088         0.193282   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.581744                       0.523939   
1                      0.606967                       0.576453   
2                      0.484859                       0.474600   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.578508                       0.743765   
1                      0.509543                       0.608839   
2                      0.488154                       0.459462   

   df_arm_length_left_avg 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   0.2                  1.393210                0.371197         0.205903   
1   1.3                  1.433549                0.361466         0.203884   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.518703                       0.550765   
1                      0.542638                       0.570462   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.466898                       0.511075   
1                      0.495546                       0.499155   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.137605                 1.213234  ...  0.297578  4.370361   
1                1.202267                 1.215584  ...  0.303999  5.345107   

      

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.200000                  1.416448                0.376279   
1  2.333333                  1.451457                0.379906   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.212547                      0.528599   
1         0.213653                      0.551580   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.534885                      0.472796   
1                       0.554157                      0.476460   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.480540                1.152981   
1                       0.488179                1.187869   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.162655  ...  0.409183  4.945505  0.121915  0.9133

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   1.4                  1.402780                0.376715         0.211378   
1   2.5                  1.413233                0.374087         0.209586   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.538215                       0.539778   
1                      0.552480                       0.564092   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.484337                       0.504653   
1                      0.492333                       0.500843   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.173456                 1.186446  ...  0.347156  6.930670   
1                1.197434                 1.210165  ...  0.375081  4.013637   

      

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.266667                  1.386698                0.369466   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.213572                      0.492917   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.488956                      0.430905   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.444881                1.066671   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.067862  ...  0.356569  5.352447  0.176653  0.909347   

   visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po   visi_sw  
0   0.891486   0.973504  0.945524  0.878891  0.999433  0.664889  

[1 rows x 49 columns]
front front dasith 2
____________________________________________________
dasith
ga

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (2, 48)
data_NaN_handled.shape (2, 48)
[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.733333                  1.309794                0.361987   
1  1.833333                  1.306318                0.358914   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.202141                      0.510886   
1         0.197855                      0.509304   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.541379                      0.406998   
1                       0.546136                      0.414441   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.431679                1.067992   
1                       0.431542                1.070638   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0           

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.466667                  1.342492                0.367463   
1  2.633333                  1.278433                0.352737   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.201396                      0.501556   
1         0.194512                      0.494608   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.554537                      0.396801   
1                       0.543737                      0.368546   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.441310                1.041384   
1                       0.452935                0.997005   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.139349  ...  0.236680  5.473207  0.110654  0.9510

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[ 1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.700000                  1.471143                0.369854   
1  1.766667                  1.458743                0.362708   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.198675                      0.520409   
1         0.194184                      0.505943   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.519675                      0.444101   
1                       0.531397                      0.453744   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.487987                1.089263   
1                       0.508357                1.080931   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.139636  ...  0.271694  6.198770  0.132325  0

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   1.3                  1.484057                0.360048         0.203027   
1   2.4                  1.481918                0.362937         0.199712   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.532814                       0.531404   
1                      0.540489                       0.529868   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.463607                       0.481231   
1                      0.478552                       0.486169   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.121015                 1.145107  ...  0.195246  3.724854   
1                1.144169                 1.148374  ...  0.146430  3.672088   

      

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.633333                  1.466795                0.364310   
1  1.366667                  1.469680                0.360798   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.200799                      0.529947   
1         0.202165                      0.516423   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.522225                      0.484781   
1                       0.518286                      0.474761   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.498669                1.134743   
1                       0.503346                1.116244   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.149693  ...  0.271407  5.432810  0.142687  0.9802

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  1.44                  1.308494                0.356865          0.18362   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.522604                       0.514079   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.426544                       0.463449   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.050107                 1.094427  ...  0.245893  5.895379   

         sw  visi_stl  visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po  \
0  0.096482  0.969308   0.980945   0.986892  0.964723  0.968674  0.999227   

    visi_sw  
0  0.973328  

[1 rows x 49 columns]
front back hasitha 3
____________________________________________________
yohan
gait_merged

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


front back yohan 1
____________________________________________________
yohan
gait_merged.shape (3, 48)
data_NaN_handled.shape (3, 48)
[ 1  1 -1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   0.8                  1.355455                0.388185         0.215050   
1   1.9                  1.333147                0.382381         0.220695   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.555251                       0.530738   
1                      0.546479                       0.537007   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.510385                       0.495228   
1                      0.521521                       0.519282   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.190012

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


gait_merged.shape (2, 48)
data_NaN_handled.shape (2, 48)
[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   0.7                  1.304334                0.379542         0.202583   
1   1.9                  1.260905                0.374540         0.201438   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.546191                       0.529915   
1                      0.534704                       0.531517   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.497509                       0.491030   
1                      0.483563                       0.485498   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.171766                 1.154526  ...  0.191782  6.323401   
1                1.148081    

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.266667                  1.423907                0.334597   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.186094                      0.533694   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.526623                      0.433388   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.484229                 1.08147   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.145573  ...  0.197074  3.201435  0.109973  0.973833   

   visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po   visi_sw  
0   0.991916   0.990761  0.977938  0.966995  0.999458  0.979399  

[1 rows x 49 columns]
front back ravindu 1
____________________________________________________
ravindu
g

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  1.52                  1.571517                0.384425         0.199587   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.585416                       0.578488   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.493323                       0.528597   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.219654                 1.241925  ...  0.146174  4.046129   

         sw  visi_stl  visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po  \
0  0.104251  0.968067   0.989554   0.987476   0.97298  0.962821  0.999201   

    visi_sw  
0  0.974307  

[1 rows x 49 columns]
front back geemanthi 1
____________________________________________________
geemanthi
gait_

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  1.52                  1.574245                0.380437         0.198510   
1  2.76                  1.526751                0.375391         0.198476   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.581776                       0.569729   
1                      0.580681                       0.573659   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.506585                       0.522848   
1                      0.494182                       0.518566   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.225977                 1.229190  ...  0.181909  3.139739   
1                1.212002                 1.219709  ...  0.218667  3.027141   

      

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[-1  1  1]
Number of outliers detected: 1
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0  1.56                  1.346780                0.381439         0.193879   
1  2.72                  1.345431                0.376646         0.198723   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.534654                       0.547334   
1                      0.529028                       0.530613   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.403206                       0.419019   
1                      0.402705                       0.412740   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.057021                 1.086165  ...  0.060865  6.213648   
1                1.055901                 1.063932  ...  0.102838  6.072834   

 

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


front back jayasanka 3
____________________________________________________
derek
gait_merged.shape (1, 48)
data_NaN_handled.shape (1, 48)
[1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 1
data_outliered.shape (1, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   1.1                  1.393556                 0.36872         0.190128   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.546856                       0.563671   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.500245                       0.512709   

   df_arm_length_left_avg  df_arm_length_right_avg  ...      fll        po  \
0                1.170798                 1.210452  ...  0.19588  4.775415   

        sw  visi_stl  visi_hakr  visi_hakl  visi_flr  visi_fll   visi_po  \
0  0.10552  0.966729   0.980939   0.978262  0.965491  0.968018  0.999492   

    vis

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
   time  df_lower_body_length_avg  df_shoulder_length_avg  df_hip_size_avg  \
0   1.2                  1.415925                0.374273         0.192432   
1   2.1                  1.417157                0.363552         0.187527   

   df_upper_arm_length_left_avg  df_upper_arm_length_right_avg  \
0                      0.552527                       0.564519   
1                      0.546070                       0.567276   

   df_lower_arm_length_left_avg  df_lower_arm_length_right_avg  \
0                      0.482791                       0.517807   
1                      0.495015                       0.515852   

   df_arm_length_left_avg  df_arm_length_right_avg  ...       fll        po  \
0                1.147386                 1.214969  ...  0.178161  4.615422   
1                1.163445                 1.216143  ...  0.144897  3.124760   

      

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  0.533333                  1.329170                0.371523   
1  1.400000                  1.378899                0.379732   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.197671                      0.542224   
1         0.201189                      0.552504   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.542624                      0.446121   
1                       0.532189                      0.453694   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.461016                1.095318   
1                       0.471014                1.118514   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.131862  ...  0.235897  6.716473  0.147667  0.9792

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.200000                  1.299448                0.355664   
1  1.966667                  1.328973                0.350188   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.196863                      0.517743   
1         0.197080                      0.522804   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.511720                      0.391562   
1                       0.519177                      0.432234   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.449041                1.010870   
1                       0.445266                1.073068   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.081270  ...  0.288497  7.138781  0.147180  0.9862

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.000000                  1.342393                0.359179   
1  2.133333                  1.341441                0.346554   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.195198                      0.523528   
1         0.192767                      0.511943   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                       0.517666                      0.415610   
1                       0.520059                      0.422142   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.429810                1.050326   
1                       0.426507                1.052284   

   df_arm_length_right_avg  ...       fll        po        sw  visi_stl  \
0                 1.067108  ...  0.255755  6.370215  0.153747  0.9864

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


[1 1]
Number of outliers detected: 0
Number of data points remaining after outlier removal: 2
data_outliered.shape (2, 49)
       time  df_lower_body_length_avg  df_shoulder_length_avg  \
0  1.166667                  1.286199                0.305681   
1  1.933333                  1.340233                0.360805   

   df_hip_size_avg  df_upper_arm_length_left_avg  \
0         0.167249                      0.535038   
1         0.204386                      0.523064   

   df_upper_arm_length_right_avg  df_lower_arm_length_left_avg  \
0                        0.53385                      0.360147   
1                        0.50872                      0.379046   

   df_lower_arm_length_right_avg  df_arm_length_left_avg  \
0                       0.439029                1.022239   
1                       0.430245                1.016519   

   df_arm_length_right_avg  ...       fll         po        sw  visi_stl  \
0                 1.104895  ...  0.173787  42.675019  0.125828  0.96

/home/cbk/anaconda3/envs/python38/lib/python3.8/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(
